### ISSUE TITLE
Help Request - Crash

### ISSUE THREAD

**Issue by walkerjonny** [citrix/PublishURLContent#5]
I've installed the newest XenApp and XenDesktop Remote PowerShell SDK 7.18.0.17
.Net Framework 4.6 has been added as feature on my server and the server is patched with the newest v4.7.2
I've copied the program to C:\Program Files\PublishURLContent.
As this is my Template VM for MSC I haven't integrated it into the Citrix Studio in a machine catalog and delivery group yet.
When I try to start is the program simply crashes with the following .NET error (event viewer):

Application: PublishContent.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Channels.HttpChannelFactory`1+HttpRequestChannel+HttpChannelRequest[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].WaitForReply(System.TimeSpan)

Exception Info: System.ServiceModel.EndpointNotFoundException

Server stack trace: 
   at System.ServiceModel.Security.IssuanceTokenProviderBase`1.DoNegotiation(TimeSpan timeout)
   at System.ServiceModel.Security.SspiNegotiationTokenProvider.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.CommunicationObjectSecurityTokenProvider.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SymmetricSecurityProtocol.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.ClientSecurityChannel`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SecuritySessionSecurityTokenProvider.DoOperation(SecuritySessionOperation operation, EndpointAddress target, Uri via, SecurityToken currentToken, TimeSpan timeout)
   at System.ServiceModel.Security.SecuritySessionSecurityTokenProvider.GetTokenCore(TimeSpan timeout)
   at System.IdentityModel.Selectors.SecurityTokenProvider.GetToken(TimeSpan timeout)
   at System.ServiceModel.Security.SecuritySessionClientSettings`1.ClientSecuritySessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open()
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Messaging.IMessage)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(System.Runtime.Remoting.Proxies.MessageData ByRef, Int32)
   at System.ServiceModel.ICommunicationObject.Open()
   at Citrix.Broker.Admin.SDK.AdminConnection..ctor(ConnectionSpec)

Exception Info: System.ServiceModel.CommunicationException
   at Citrix.Broker.Admin.SDK.AdminConnection..ctor(ConnectionSpec)
   at Citrix.Broker.Admin.SDK.AdminConnection.GetAdminConnection(System.String, System.Nullable`1<Citrix.Broker.Admin.SDK.SdkBinding>, Boolean, System.String, Boolean)
   at Citrix.Broker.Admin.SDK.WCFCmdletBase.BeginProcessing()

Exception Info: Citrix.Broker.Admin.SDK.SdkOperationException
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(System.Management.Automation.ErrorRecord)

Exception Info: System.Management.Automation.CmdletInvocationException
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(System.Collections.IEnumerable)
   at System.Management.Automation.PowerShell+Worker.ConstructPipelineAndDoWork(System.Management.Automation.Runspaces.Runspace, Boolean)
   at System.Management.Automation.PowerShell+Worker.CreateRunspaceIfNeededAndDoWork(System.Management.Automation.Runspaces.Runspace, Boolean)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.PowerShell.CoreInvoke[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.PowerShell.CoreInvoke[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.IEnumerable, System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.PowerShell.Invoke(System.Collections.IEnumerable, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.PowerShell.Invoke()
   at PublishContent.MainForm.loadDeliveryGroups()
   at PublishContent.MainForm..ctor()
   at PublishContent.Program.Main()

Is this related to the situation that this Template VM first needs to be integrated into my farm (added into a Machine Catalog & Delivery Group) first for this application to load properly?

**Comment by johnmcbride** [comment]
@walkerjonny First, thank you for the comment and stack trace. To be honest I haven't testing on a template VM at this point, but I think you're spot on with your comment about error out because its a template VM and not necessarily in the environment yet (from my understanding). If you check out lines 34-36 in the [MainForm.cs file](https://github.com/citrix/PublishURLContent/blob/9634cff70b89ab056d3f879ecce38eb31b64c901/src/MainForm.cs#L33-L36) you can see we are loading the citrix powershell cmdlets and trying to get the delivery groups when the application loads. This might be causing an error in that the machine is not in the environment. 

Do you have an environment where you might be able to help debug? It'll take a little while here to get an environment spin up for testing.

**Comment by walkerjonny** [comment]
I should be ready to check this out within a few days because my Template VM is nearly ready to be used as a master image for my MCS catalog.
As soon as I have set up some VMs based on this master image and created a delivery group for them I'll report back.

**Comment by johnmcbride** [comment]
Thanks @walkerjonny Copy any findings here in this issue and we can work through them
